<?php

namespace AppBundle\Repository;

/**
 * AdminConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminConfigRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySlug($slug)
    {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
            ->from($this->_entityName, 'c')
            ->where( 'c.slug = :slug')
            ->setParameter('slug', $slug );
        return $qb->getQuery()->getOneOrNullResult();
    }
}
