<?php

namespace AppBundle\Repository;

/**
 * BidDefinitionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BidDefinitionsRepository extends \Doctrine\ORM\EntityRepository
{
}
