<?php

namespace AppBundle\Repository;

/**
 * BidLicenseTermItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BidLicenseTermItemRepository extends \Doctrine\ORM\EntityRepository
{
}
