<?php

namespace AppBundle\Repository;

/**
 * BidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BidRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPendingBids($company){
        $now = date('Y-m-d H:i:s');
        $query = $this->createQueryBuilder('b')
            ->orderBy("b.createdAt", "DESC")
            ->join('b.content', 'c')
            ->join('b.salesPackage', 'bundle')
            ->join('b.status', 'status')
            ->join('b.type', 'type')
            ->where('b.buyerCompany = :company')
            ->andWhere('status.name = :pending')
            ->andWhere('type.name = :type')
            ->andWhere('bundle.sold = :isSold')
            ->andWhere(':now < c.expiresAt')
            ->setParameter('now',$now)
            ->setParameter('pending', 'PENDING')
            ->setParameter('type', 'BIDDING')
            ->setParameter('company', $company)
            ->setParameter('isSold', false)
            ->getQuery();

        return $query->getResult();
    }

    public function getRejectedBids($company){
        $now = date('Y-m-d H:i:s');
        $query = $this->createQueryBuilder('b')
            ->orderBy("b.updatedAt", "DESC")
            ->join('b.content', 'c')
            ->join('b.salesPackage', 'bundle')
            ->join('b.status', 'status')
            ->join('b.type', 'type')
            ->where('b.buyerCompany = :company')
            ->andWhere('status.name = :rejected or :now > c.expiresAt or bundle.sold = :isSold')
            ->andWhere('type.name = :type')
            ->andWhere('status.name != :approved')
            ->setParameter('now',$now)
            ->setParameter('rejected', 'REJECTED')
            ->setParameter('approved', 'APPROVED')
            ->setParameter('type', 'BIDDING')
            ->setParameter('company', $company)
            ->setParameter('isSold', true)
            ->getQuery();

        return $query->getResult();
    }

    public function getPendingBidsByContent($content){
        $query = $this->createQueryBuilder('b')
            ->join('b.status', 'status')
            ->join('b.type', 'type')
            ->where('b.content = :content')
            ->andWhere('status.name = :pending')
            ->andWhere('type.name = :type')
            ->setParameter('pending', 'PENDING')
            ->setParameter('type', 'BIDDING')
            ->setParameter('content', $content)
            ->getQuery();

        return $query->getResult();
    }

    public function getAllBidsByContent($content){
        $query = $this->createQueryBuilder('b')
            ->orderBy("b.createdAt", "DESC")
            ->where('b.content = :content')
            ->setParameter('content', $content)
            ->getQuery();

        return $query->getResult();
    }

    public function getAllCustomBidsByContent($content){
        $query = $this->createQueryBuilder('b')
            ->join('b.salesPackage', 'bundle')
            ->orderBy("b.createdAt", "DESC")
            ->where('b.content = :content')
            ->andWhere('bundle.custom = :custom')
            ->setParameter('content', $content)
            ->setParameter('custom', true)
            ->getQuery();

        return $query->getResult();
    }

    public function getAllBidsByContentAndUser($content, $company){
        $query = $this->createQueryBuilder('b')
            ->orderBy("b.createdAt", "DESC")
            ->where('b.content = :content')
            ->andWhere('b.buyerCompany = :buyerCompany')
            ->setParameter('content', $content)
            ->setParameter('buyerCompany', $company)
            ->getQuery();

        return $query->getResult();
    }

    public function getAllBidsBySalesBundle($salesBundle){
        $query = $this->createQueryBuilder('b')
            ->orderBy("b.createdAt", "DESC")
            ->where('b.salesPackage = :salesBundle')
            ->setParameter('salesBundle', $salesBundle)
            ->getQuery();

        return $query->getResult();
    }

    public function getClosedDealsBySalesBundle($salesBundle){
        $query = $this->createQueryBuilder('b')
            ->orderBy("b.createdAt", "DESC")
            ->join('b.status', 'status')
            ->where('b.salesPackage = :salesBundle')
            ->andWhere('status.name = :approved')
            ->setParameter('approved', 'APPROVED')
            ->setParameter('salesBundle', $salesBundle)
            ->getQuery();

        return $query->getResult();
    }

    public function getAllBids($user){
        $query = $this->createQueryBuilder('b')
            ->join('b.content', 'c')
            ->join('b.status', 'status')
            ->join('b.type', 'type')
            ->where('b.buyerUser = :user')
            ->setParameter('user', $user)
            ->getQuery();

        return $query->getResult();
    }

    public function getClosedBids($company){
        $query = $this->createQueryBuilder('b')
            ->orderBy("b.createdAt", "DESC")
            ->join('b.content', 'c')
            ->join('b.status', 'status')
            ->where('b.buyerCompany = :company')
            ->andWhere('status.name = :approved')
            ->setParameter('approved', 'APPROVED')
            ->setParameter('company', $company)
            ->getQuery();

        return $query->getResult();
    }

}
