<?php

namespace AppBundle\Repository;

/**
 * BidStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BidStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
