<?php

namespace AppBundle\Repository;

/**
 * BidTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BidTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
