<?php

namespace AppBundle\Repository;

/**
 * CompanySnapshotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanySnapshotRepository extends \Doctrine\ORM\EntityRepository
{
}
