<?php

namespace AppBundle\Repository;

/**
 * CompanyDefinitionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyDefinitionsRepository extends \Doctrine\ORM\EntityRepository
{
}
