<?php

namespace AppBundle\Repository;

/**
 * ContentSelectedRightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentSelectedRightRepository extends \Doctrine\ORM\EntityRepository
{
}
