<?php

namespace AppBundle\Repository;

/**
 * ListingRightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealRightRepository extends \Doctrine\ORM\EntityRepository
{
}
