<?php

namespace AppBundle\Repository;

/**
 * DistributionPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributionPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
