<?php

namespace AppBundle\Repository;

/**
 * EditedProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditedProgramRepository extends \Doctrine\ORM\EntityRepository
{
}
