<?php

namespace AppBundle\Repository;

/**
 * FixtureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FixtureRepository extends \Doctrine\ORM\EntityRepository
{
}
