<?php

namespace AppBundle\Repository;

/**
 * InstallmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstallmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
