<?php

namespace AppBundle\Repository;

/**
 * LicenseAgreementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenseAgreementRepository extends \Doctrine\ORM\EntityRepository
{
}
