<?php

namespace AppBundle\Repository;

/**
 * ListingLastActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingLastActionRepository extends \Doctrine\ORM\EntityRepository
{
}
