<?php

namespace AppBundle\Repository;

/**
 * ListingStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
