<?php

namespace AppBundle\Repository;

/**
 * MatchGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchGameRepository extends \Doctrine\ORM\EntityRepository
{
}
