<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{

    public function getThreadMessages($thread)
    {
        $query = $this->createQueryBuilder('m')
            ->where('m.thread = :thread')
            ->setParameter('thread', $thread)
            ->getQuery();

        return $query->getResult();
    }

    public function getThreadLastMessage($thread)
    {
        $query = $this->createQueryBuilder('m')
            ->where('m.thread = :thread')
            ->setParameter('thread', $thread)
            ->orderBy("m.createdAt", "DESC")
            ->setMaxResults(1)
            ->getQuery();

        return $query->getResult();
    }
}
