<?php

namespace AppBundle\Repository;

/**
 * NotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUnseenByUserExcludingType($user, $type){


        return $this->createQueryBuilder('notification')
            ->where('notification.seen = :seen')
            ->andWhere('notification.user = :user')
            ->andWhere('notification.type != :type')
            ->setParameter('user',$user)
            ->setParameter('seen', false)
            ->setParameter('type', $type)
            //->orderBy('c.createdAt','DESC')
            ->getQuery()->getResult();
    }
}
