<?php

namespace AppBundle\Repository;

/**
 * PropertyRightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRightRepository extends \Doctrine\ORM\EntityRepository
{
}
