<?php

namespace AppBundle\Repository;

/**
 * CompanyLicenseTermItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyLicenseTermItemRepository extends \Doctrine\ORM\EntityRepository
{
}
