<?php

namespace AppBundle\Repository;

/**
 * RightsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightsRepository extends \Doctrine\ORM\EntityRepository
{
}
