<?php

namespace AppBundle\Repository;

/**
 * RightsContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightsContentRepository extends \Doctrine\ORM\EntityRepository
{
}
