<?php

namespace AppBundle\Repository;

/**
 * RightsPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightsPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
