<?php

namespace AppBundle\Repository;

/**
 * RightsItemContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightsItemContentRepository extends \Doctrine\ORM\EntityRepository
{
}
