<?php

namespace AppBundle\Repository;

/**
 * RightsItemContentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightsItemContentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
