<?php

namespace AppBundle\Repository;

/**
 * RightsGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightsGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
