<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Rights;

/**
 * RightsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $packages
     * @param $group
     * @return Rights []
     */
    public function getByPackagesAndGroup( $packages, $group ){

        return
            $this->createQueryBuilder('rights')
                ->select('rights')
                ->where( 'rights.group = :group')
                ->leftJoin('rights.packages', 'rights_package')
                ->andWhere( 'rights_package.id IN (:packages)')
                ->groupBy('rights.id')
                ->setParameter('packages', $packages )
                ->setParameter('group', $group )
                ->getQuery()
                ->getResult();
                //->getArrayResult();

    }
}
