<?php

namespace AppBundle\Repository;

/**
 * SalesPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
