<?php

namespace AppBundle\Repository;

/**
 * SourceDefinitionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceDefinitionsRepository extends \Doctrine\ORM\EntityRepository
{
}
