<?php

namespace AppBundle\Repository;

/**
 * SourceLicenseTermItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceLicenseTermItemRepository extends \Doctrine\ORM\EntityRepository
{
}
