<?php

namespace AppBundle\Repository;

/**
 * SourceLicenseTermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceLicenseTermRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSortedTerms(  ){

        $query = $this->createQueryBuilder('term');

        $query
            ->addOrderBy('term.position', 'ASC');

        $result = $query->getQuery()->getResult();

        return $result;

    }
}
