<?php

namespace AppBundle\Repository;

/**
 * SourceLicenseTermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceLicenseTermRepository extends \Doctrine\ORM\EntityRepository
{
}
