<?php

namespace AppBundle\Repository;

/**
 * SportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearchResultsByName($name){
        $qb = $this->_em->createQueryBuilder();

        $qb->select('s')
            ->from($this->_entityName, 's')
            ->where( 's.name like :name')
            ->setMaxResults(60)
            ->setParameter('name', $name );

        return $qb->getQuery()->getArrayResult();
    }

    public function findAll()
    {
        return $this->findBy(array(), array('name' => 'ASC'));
    }

    public function findAllByFlag( $flags )
    {
        $criteria = array();

        if ( $flags != null && is_array($flags)){
            if (in_array("create", $flags)) $criteria["shownInCreate"] = true;
            if (in_array("wall", $flags)) $criteria["shownInWall"] = true;
            if (in_array("top", $flags)) $criteria["topSport"] = true;
        }

        return $this->findBy($criteria, array('name' => 'ASC'));
    }
}
