<?php

namespace AppBundle\Repository;

/**
 * SportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearchResultsByName($name){
        $qb = $this->_em->createQueryBuilder();

        $qb->select('s')
            ->from($this->_entityName, 's')
            ->where( 's.name like :name')
            ->setMaxResults(60)
            ->setParameter('name', $name );

        return $qb->getQuery()->getArrayResult();
    }
}
