<?php

namespace AppBundle\Repository;

/**
 * SportCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
