<?php

namespace AppBundle\Repository;

/**
 * SportCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearchResultsByName($name){
        $qb = $this->_em->createQueryBuilder();

        $qb->select('sc')
            ->from($this->_entityName, 'sc')
            ->where( 'sc.name like :name')
            ->setMaxResults(60)
            ->setParameter('name', $name );

        return $qb->getQuery()->getArrayResult();
    }

    public function getCountries(){
        return $this->createQueryBuilder('sc')
            ->where('sc.countryCode IS NOT NULL')
            ->andWhere('sc.countryCode != :identifier')
            ->groupBy("sc.countryCode")
            ->setParameter('identifier', "")
            ->getQuery()
            ->getArrayResult();
    }
}
