<?php

namespace AppBundle\Repository;

/**
 * TerritoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerritoryRepository extends \Doctrine\ORM\EntityRepository
{
}
