<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Company;

/**
 * ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllThreads(Company $company)
    {
        $query = $this->createQueryBuilder('t')
            ->where('t.ownerCompany = :company or t.buyerCompany = :company')
            ->setParameter('company', $company)
            ->getQuery();

        return $query->getResult();
    }
}
