<?php

namespace AppBundle\Repository;

/**
 * RolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatusRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByName($name)
    {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
            ->from($this->_entityName, 'c')
            ->where( 'c.name = :name')
            ->setParameter('name', $name );
        return $qb->getQuery()->getOneOrNullResult();
    }

}
