<?php

namespace AppBundle\Repository;

/**
 * WatchlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatchlistRepository extends \Doctrine\ORM\EntityRepository
{
}
