easy_admin:
    site_name: 'Content Arena'
    design:
        menu:
            - Content
            - label: 'User Information'
              children: ['User', 'Company', 'Status']
            - Deals
            - RightsPackage
            - label: 'Sports'
              children: ['Sport', 'SportCategory', 'Tournament', 'Season']
            - label: 'Custom Text'
              children: ['EmailContent']
            - Country

        form_theme:
            - 'horizontal'
            # the following Twig template can be located anywhere in the application.
            # it can also be added to the twig.form_themes option to use it in the
            # entire application, not only the backend
            - 'easy_admin/basic.form.html.twig'

    entities:
            User:
                class: AppBundle\Entity\User
                list:
                    fields: ['id', 'firstName', 'lastName', 'email', 'approved', 'autoPublish']

                form:
                    fields:
                        - 'email'
                        - 'firstName'
                        - 'lastName'
                        - 'status'
                        - 'title'
                        - 'phone'
                        - 'country'
                        - 'company'
                    actions:
                        - { name: 'sendActivationLink', css_class : 'btn btn-primary' }
                        - { name: 'createCompany', css_class : 'btn btn-primary' }

            Company:
                class: AppBundle\Entity\Company
                controller: AppBundle\Controller\Admin\CompanyController
            Content:
                class: AppBundle\Entity\Content
                form:
                    fields:
                        - { property: 'name' }
                        - { property: 'sports' }
                        - { property: 'tournament' }
                        - { property: 'rightsPackage' }
                        - { property: 'status' }
                        - { property: 'expiresAt' }
                list:
                    fields:
                        - { property: 'id' }
                        - { property: 'customId' }
                        #- { property: 'company' }
                        - { property: 'name' }
                        - { property: 'createdAt' }
                        - { property: 'expiresAt' }
                        - { property: 'image', type: 'image', base_path: '%admin_uploads_uri%' }
                        #- { property: 'ownLicense', template: ':easy_admin:license.list.html.twig', base_path: '%admin_uploads_uri%' }
                        - { property: 'status' }
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
            Deals:
                class: AppBundle\Entity\Bid
            Country:
                class: AppBundle\Entity\Country
            Status:
                class: AppBundle\Entity\UserStatus
            RightsPackage:
                class: AppBundle\Entity\RightsPackage
                label: 'Super Rights'
                list:
                    title: 'Super Rights'
                    fields:
                        - 'name'
                        - 'shortLabel'
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
                form:
                    title: 'Super Rights'
                    fields:
                        - 'name'
                        - 'shortLabel'
            Rights:
                class: AppBundle\Entity\Rights
                label: 'Rights'
                list:
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
            RightsItemContent:
                class: AppBundle\Entity\RightsItemContent
                label: 'Rights Items'
                form:
                    label: 'Rights Items'
                    fields:
                        - 'name'
                        - 'form_content'
                        - 'contract_content'
                        - 'description'
                        - 'children'
                        - { property: 'not_optional', type: 'checkbox' }
                list:
                    label: 'Rights Items'
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
            EmailContent:
                class: AppBundle\Entity\EmailContent
                label: 'Email Content'
                list:
                    fields: ['slug', 'description', 'content']
                    actions:
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
                form:
                    fields: ['slug', 'description', 'content']
            Sport:
                class: AppBundle\Entity\Sport
            SportCategory:
                class: AppBundle\Entity\SportCategory
            Tournament:
                class: AppBundle\Entity\Tournament
            Season:
                class: AppBundle\Entity\Season
knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
