easy_admin:
    site_name: 'Content Arena'
    design:
        menu:
            - Content
            - label: 'User Information'
              children:
                  - User
                  - Company
                  - Status
                  - {label: 'Import', icon: 'file-new', route: 'importUsersPage'}
                  - {label: 'Export', icon: 'file-new', route: 'exportUsersPage'}
            - Deals
            - RightsPackage
            - label: 'Sports'
              children: ['Sport', 'SportCategory', 'SportsGroup', 'Tournament', 'Season']
            - label: 'Custom Text'
              children: ['EmailContent']
            - label: 'Utils'
              children:
                - {label: 'View LA General Terms', icon: 'file-new', route: 'contractTestGeneral', target: '_blank'}
                - {label: 'Upload General Terms Page', icon: 'file-new', route: 'uploadGeneralTermsPage'}
                - {label: 'Upload LA General Terms', icon: 'file-new', route: 'uploadGeneralTerms'}
                - {label: 'Upload Localization File', icon: 'file-new', route: 'uploadLocales'}
            - Country
            - Terms
            - TermItems
            - Definitions

        assets:
            js:
                - 'bundles/app/admin/javascript/admin.js'
    entities:
            User:
                class: AppBundle\Entity\User
                list:
                    fields: ['id', 'firstName', 'lastName', 'email', 'company', 'status', 'lastLogin']
                    actions:
                        - { name: 'show' }
                        - { name: 'edit' }
                        - { name: 'delete' }
                show:
                    fields:
                        - { property: 'email' }
                        - { property: 'firstName' }
                        - { property: 'lastName' }
                        - { property: 'status' }
                        - { property: 'title' }
                        - { property: 'phone' }
                        - { property: 'country' }
                        - { property: 'company' }
                        - { property: 'applicationCompany' }
                        - { property: 'preferredProfile' }
                        - { property: 'preferredBuyerCountries' }
                        - { property: 'preferredBuyerSports' }
                        - { property: 'preferredSellerSports' }
                        #- { property: 'confirmationToken', label: 'Activation Code' }
                        - { property: 'confirmationToken', template: 'easy_admin/activation.code.list.html.twig', base_path: '%carena_host_url%' }
                        - { property: 'autoPublish' }
                edit:
                    fields:
                        - { property: 'email' }
                        - { property: 'firstName' }
                        - { property: 'lastName' }
                        - { property: 'status' }
                        - { property: 'title' }
                        - { property: 'phone' }
                        - { property: 'country' }
                        - { property: 'company' }
                        - { property: 'applicationCompany' }
                        - { property: 'preferredProfile' }
                        - { property: 'preferredBuyerCountries' }
                        - { property: 'preferredBuyerSports' }
                        - { property: 'preferredSellerSports' }
                        - { property: 'confirmationToken', label: 'Activation Code' }
                        #- { property: 'confirmationToken', template: ':easy_admin:activation.code.list.html.twig', base_path: '%admin_uploads_uri%' }
                        - { property: 'autoPublish' }
                    actions:
                        - { name: 'sendActivationLink', css_class : 'btn btn-primary' }
                        - { name: 'createActivationLink', css_class : 'btn btn-primary' }
                        - { name: 'createCompany', css_class : 'btn btn-primary' }

            Company:
                class: AppBundle\Entity\Company
                controller: AppBundle\Controller\Admin\CompanyController
            Content:
                class: AppBundle\Entity\Content
                controller: AppBundle\Controller\Admin\AdminContentController
                sort: 'status'
                form:
                    fields:
                        - { property: 'name' }
                        - { property: 'sports' }
                        - { property: 'tournament' }
                        - { property: 'rightsPackage' }
                        - { property: 'status' }
                        - { property: 'expiresAt' }
                        - { property: 'featured' }
                        - { property: 'featuredPosition' }
                    actions:
                        - { name: 'notifyUsersAboutListing', css_class : 'btn btn-primary' }
                search:
                    fields:
                        - 'customId'
                        - 'name'
                        - 'sports'
                        - 'tournament.name'
                        - 'status.name'
                        - 'signatureName'
                        - 'signaturePosition'
                        - 'description'
                        - 'programDescription'
                    dql_filter: "status.name != 'SOLD_COPY'"
                list:
                    dql_filter: "status.name != 'SOLD_COPY'"
                    sort: 'status'
                    fields:
                        - { property: 'id' }
                        - { property: 'customId' }
                        #- { property: 'company' }
                        - { property: 'name' }
                        - { property: 'createdAt' }
                        - { property: 'expiresAt' }
                        - { property: 'featured' }
                        - { property: 'featuredPosition' }
                        - { property: 'image', type: 'image', base_path: '%admin_uploads_uri%' }
                        - { property: 'status' }
                        - { property: 'shareId', template: 'share.listing.list.html.twig', base_path: '%carena_host_url%', label: "Share" }
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
            Deals:
                class: AppBundle\Entity\Bid
            Country:
                class: AppBundle\Entity\Country
            Status:
                class: AppBundle\Entity\UserStatus
            RightsPackage:
                class: AppBundle\Entity\RightsPackage
                label: 'Super Rights'
                list:
                    title: 'Super Rights'
                    fields:
                        - 'name'
                        - 'shortLabel'
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
                form:
                    title: 'Super Rights'
                    fields:
                        - 'name'
                        - 'shortLabel'
            Rights:
                class: AppBundle\Entity\Rights
                label: 'Rights'
                list:
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
            RightsItemContent:
                class: AppBundle\Entity\RightsItemContent
                label: 'Rights Items'
                form:
                    label: 'Rights Items'
                    fields:
                        - 'name'
                        - 'form_content'
                        - 'contract_content'
                        - 'description'
                        - 'children'
                        - { property: 'not_optional', type: 'checkbox' }
                list:
                    label: 'Rights Items'
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
            EmailContent:
                class: AppBundle\Entity\EmailContent
                label: 'Email Content'
                list:
                    fields: ['slug', 'description', 'content']
                    actions:
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
                form:
                    fields: ['slug', 'description', 'content']
            Sport:
                class: AppBundle\Entity\Sport
            SportCategory:
                class: AppBundle\Entity\SportCategory
            SportsGroup:
                class: AppBundle\Entity\SportsGroup
            Tournament:
                class: AppBundle\Entity\Tournament
            Season:
                class: AppBundle\Entity\Season
            Terms:
                class: AppBundle\Entity\SourceLicenseTerm
            Definitions:
                class: AppBundle\Entity\SourceDefinitions
            TermItems:
                class: AppBundle\Entity\SourceLicenseTermItem
                label: 'Term Items'
                list:
                    fields: ['term', 'position', 'editable', 'content']

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
