easy_admin:
    site_name: 'Content Arena'
    design:
        menu:
            - Content
            - label: 'User Information'
              children:
                - User
                - Status
                - { entity: 'ArchivedUser', label: 'Archived' }
                - {label: 'Import', icon: 'file-new', route: 'importUsersPage'}
                - {label: 'Export', icon: 'file-new', route: 'exportUsersPage'}
                - {label: 'Archive from file', icon: 'file-new', route: 'importAndArchive'}
            - label: 'Company Information'
              children:
                - Company
                - {label: 'Import data', icon: 'file-new', route: 'importCompaniesPage'}
                - {label: 'Export', icon: 'file-new', route: 'exportCompaniesPage'}
            - Deals
            - RightsPackage
            - label: 'Sports'
              children: ['Sport', 'SportCategory', 'SportsGroup', 'Tournament', 'Season']
            - label: 'Custom Text'
              children: ['EmailContent']
            - label: 'Utils'
              children:
                - Language
                - Translation
                - {label: 'Import translations', icon: 'file-new', route: 'uploadLocales'}
            - Country
            - label: 'License Agreement'
              children:
                - Terms
                - TermItems
                - Definitions
            - AdminConfig
            - label: 'Marketplace'
              url: '/marketplace'
              rel: 'index'

        assets:
            js:
                - 'bundles/app/admin/javascript/admin.js'
            css:
                - 'bundles/app/admin/css/admin.css'
    entities:
            User:
                class: AppBundle\Entity\User
                controller: AppBundle\Controller\Admin\AdminUserController
                search:
                    fields:
                        - 'email'
                        - 'firstName'
                        - 'lastName'
                        - 'title'
                        - 'status.name'
                        - 'country'
                        - 'company'
                        - 'applicationCompany'
                        - 'notes'
                list:
                    dql_filter: "status.name != 'Archived' OR entity.status is NULL"
                    fields: ['id', 'firstName', 'lastName', 'email', 'company', 'status', 'lastLogin']
                    actions:
                        - { name: 'show' }
                        - { name: 'edit' }
                        - { name: 'delete' }
                        - { name: 'switchUser', label: "Switch" }
                        - { name: 'archiveUser', label: "Archive" }
                show:
                    fields:
                        - { property: 'email' }
                        - { property: 'firstName' }
                        - { property: 'lastName' }
                        - { property: 'status' }
                        - { property: 'title' }
                        - { property: 'phone' }
                        - { property: 'country' }
                        - { property: 'company' }
                        - { property: 'company.country', label: "Company Country" }
                        - { property: 'company.region', label: "Company Region" }
                        - { property: 'company.category', label: "Company Category" }
                        - { property: 'applicationCompany' }
                        - { property: 'preferredProfile' }
                        - { property: 'preferredBuyerCountries' }
                        - { property: 'preferredBuyerSports' }
                        - { property: 'preferredSellerSports' }
                        #- { property: 'confirmationToken', label: 'Activation Code' }
                        - { property: 'confirmationToken', template: 'easy_admin/activation.code.list.html.twig', base_path: '%carena_host_url%' }
                        - { property: 'autoPublish' }
                        - { property: 'notes' }
                form:
                    fields:
                        - { property: 'email' }
                        - { property: 'firstName' }
                        - { property: 'lastName' }
                        - { property: 'company', type_options: { required: true }}
                        - { property: 'applicationCompany' }
                        - { property: 'title', label: 'Position' }
                        - { property: 'phone' }
                        - { property: 'country' }
                        - { property: 'autoPublish' }
                        - { property: 'notes', type_options: { required: false, attr: { class: 'notes-text-area' } } }
                edit:
                    fields:
                        - { property: 'email' }
                        - { property: 'firstName' }
                        - { property: 'lastName' }
                        - { property: 'status' }
                        - { property: 'title' }
                        - { property: 'phone' }
                        - { property: 'country' }
                        - { property: 'company' }
                        - { property: 'applicationCompany' }
                        - { property: 'preferredProfile' }
                        - { property: 'preferredBuyerCountries' }
                        - { property: 'preferredBuyerSports' }
                        - { property: 'preferredSellerSports' }
                        - { property: 'confirmationToken', label: 'Activation Code' }
                        #- { property: 'confirmationToken', template: ':easy_admin:activation.code.list.html.twig', base_path: '%admin_uploads_uri%' }
                        - { property: 'autoPublish' }
                        - { property: 'notes', type_options: { required: false, attr: { class: 'notes-text-area' } } }
                    actions:
                        - { name: 'sendActivationLink', css_class : 'btn btn-primary' }
                        - { name: 'createActivationLink', css_class : 'btn btn-primary' }
                        - { name: 'createCompany', css_class : 'btn btn-primary' }
            ArchivedUser:
                class: AppBundle\Entity\User
                controller: AppBundle\Controller\Admin\AdminUserController
                search:
                    fields:
                        - 'email'
                        - 'firstName'
                        - 'lastName'
                        - 'title'
                        - 'status.name'
                        - 'country'
                        - 'company'
                        - 'applicationCompany'
                        - 'notes'
                list:
                    dql_filter: "status.name = 'Archived'"
                    fields: ['id', 'firstName', 'lastName', 'email', 'company', 'status', 'lastLogin']
                    actions:
                        - { name: 'show' }
                        - { name: 'edit' }
                        - { name: 'delete' }
            Company:
                class: AppBundle\Entity\Company
                list:
                    fields:
                        - { property: 'legalName' }
                        - { property: 'category' }
                        - { property: 'country', label: 'Company Country'}
                        - { property: 'region', label: 'Company Region' }
                        - { property: 'sport', label: 'Fed/Club/League Sport' }
                        - { property: 'website'}
                        - { property: 'createdAt'}
                    actions:
                        - { name: 'show' }
                        - { name: 'edit' }
                        - { name: 'delete' }
                form:
                    fields:
                        - { property: 'legalName' }
                        - { property: 'country', label: 'Company Country', type_options: { required: true }}
                        - { property: 'website', type_options: { required: true } }
                        - { property: 'category', type_options: { required: true } }
                        - { property: 'region', label: 'Company Region'  }
                        - { property: 'sport', label: 'Fed/Club/League Sport' }
                        - { property: 'city' }
                        - { property: 'address' }
                        - { property: 'address2' }
                        - { property: 'zip' }
                        - { property: 'phone' }
                        - { property: 'vat' }
                        - { property: 'registrationNumber' }
                        - { property: 'users' }
                        - { property: 'description' }
                        - { property: 'owner' }
                        - { property: 'notes', type_options: { required: false, attr: { class: 'notes-text-area' } } }
                show:
                    fields:
                        - { property: 'legalName' }
                        - { property: 'country', label: 'Company Country' }
                        - { property: 'website' }
                        - { property: 'category' }
                        - { property: 'region' , label: 'Company Region' }
                        - { property: 'sport', label: 'Fed/Club/League Sport' }
                        - { property: 'city' }
                        - { property: 'address' }
                        - { property: 'address2' }
                        - { property: 'zip' }
                        - { property: 'phone' }
                        - { property: 'vat' }
                        - { property: 'registrationNumber' }
                        - { property: 'users' }
                        - { property: 'description' }
                        - { property: 'owner' }
                        - { property: 'createdAt'}
                        - { property: 'notes', type_options: { attr: { class: 'notes-text-area' } } }

                controller: AppBundle\Controller\Admin\AdminCompanyController
            Content:
                class: AppBundle\Entity\Content
                controller: AppBundle\Controller\Admin\AdminContentController
                templates:
                    list: 'content/list.html.twig'
                sort: 'status'
                form:
                    fields:
                        - { property: 'name' }
                        - { property: 'sports' }
                        - { property: 'tournament' }
                        - { property: 'rightsPackage' }
                        - { property: 'status' }
                        - { property: 'expiresAt' }
                        - { property: 'featured' }
                        - { property: 'featuredPosition' }
                        - { property: 'relevance' }
                    actions:
                        - { name: 'notifyUsersAboutListing', css_class : 'btn btn-primary' }
                search:
                    fields:
                        - 'customId'
                        - 'name'
                        - 'sports'
                        - 'tournament.name'
                        - 'status.name'
                        - 'signatureName'
                        - 'signaturePosition'
                        - 'description'
                        - 'programDescription'
                    dql_filter: "status.name != 'SOLD_COPY'"
                list:
                    sort: 'status'
                    fields:
                        - { property: 'id' }
                        - { property: 'customId' }
                        - { property: 'company' }
                        - { property: 'name' }
                        - { property: 'createdAt' }
                        - { property: 'expiresAt' }
                        - { property: 'publishedAt' }
                        - { property: 'featured' }
                        - { property: 'featuredPosition' }
                        - { property: 'relevance' }
                        - { property: 'image', type: 'image', base_path: '%admin_uploads_uri%' }
                        - { property: 'status' }
                        - { property: 'shareId', template: 'share.listing.list.html.twig', base_path: '%carena_host_url%', label: "Share" }
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
            Deals:
                list:
                    sort: 'createdAt'
                    fields:
                        - { property: 'customId', sortable: false }
                        - { property: 'content', label: 'Listing', sortable: false }
                        - { property: 'amount', label: 'License fee' }
                        - { property: 'totalFee' }
                        - { property: 'createdAt' }
                        - { property: 'status' }
                        - { property: 'salesPackage.name', label: 'Bundle'}
                        - { property: 'content.company', label: 'Seller Company' }
                        - { property: 'buyerCompany', label: 'Buyer Company' }
                        - { property: 'buyerUser', label: 'Buyer User' }

                class: AppBundle\Entity\Bid
            Country:
                class: AppBundle\Entity\Country
            Status:
                class: AppBundle\Entity\UserStatus
            RightsPackage:
                class: AppBundle\Entity\RightsPackage
                label: 'Super Rights'
                list:
                    title: 'Super Rights'
                    fields:
                        - 'name'
                        - 'shortLabel'
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
                form:
                    title: 'Super Rights'
                    fields:
                        - 'name'
                        - 'shortLabel'
            Rights:
                class: AppBundle\Entity\Rights
                label: 'Rights'
                list:
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
            RightsItemContent:
                class: AppBundle\Entity\RightsItemContent
                label: 'Rights Items'
                form:
                    label: 'Rights Items'
                    fields:
                        - 'name'
                        - 'form_content'
                        - 'contract_content'
                        - 'description'
                        - 'children'
                        - { property: 'not_optional', type: 'checkbox' }
                list:
                    label: 'Rights Items'
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
            EmailContent:
                class: AppBundle\Entity\EmailContent
                label: 'Email Content'
                list:
                    fields: ['slug', 'description', 'content']
                    actions:
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
                form:
                    fields: ['slug', 'description', 'content']
            Sport:
                class: AppBundle\Entity\Sport
            SportCategory:
                class: AppBundle\Entity\SportCategory
            SportsGroup:
                class: AppBundle\Entity\SportsGroup
            Tournament:
                class: AppBundle\Entity\Tournament
            Season:
                class: AppBundle\Entity\Season
            Terms:
                class: AppBundle\Entity\SourceLicenseTerm
            Definitions:
                class: AppBundle\Entity\SourceDefinitions
            Language:
                class: Juanx\ReactTranslationBundle\Entity\Language
            Translation:
                class: Juanx\ReactTranslationBundle\Entity\Translation
                list:
                    fields: ['id', 'i18nKey', 'value', 'language']
            AdminConfig:
                class: AppBundle\Entity\AdminConfig
                label: 'Admin Config'
                list:
                    fields: ['slug', 'content']
            TermItems:
                class: AppBundle\Entity\SourceLicenseTermItem
                label: 'Term Items'
                list:
                    fields: ['term', 'position', 'editable', 'content']

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query parameter name
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
