imports:
    - { resource: config.yml }
    - { resource: parameters.yml }

parameters:
    locale: en
    google_analytics_key: 'UA-136237491-1'
    sportradar_api_token: dqahyKSX6u5J1vNHMp
    sportradar_api_host: https://api.betradar.com/v1
    carena_host_url: '%local_host%'
    app.email_alerts: '%local_email_alert_address%'
    job_account_incomplete_time: '+5 minutes'
    job_account_incomplete_from_invite_time: '+5 minutes'

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

twig:
    globals:
        frontend_url : 'http://localhost:8200/content-arena-pwire/'

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']
