imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: languages.yml }
    - { resource: "@ContentArenaLayerBundle/Resources/config/services.yml" }
    - { resource: "@ApiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    sportradar_api_token: dqahyKSX6u5J1vNHMp
    sportradar_api_host: https://api.betradar.com/v1
    sportradar_api_cache_ttl : 432000
    uploads_main_folder: '%kernel.project_dir%/web/uploads'
    uploads_uri_prefix: 'uploads'
    admin_uploads_uri: ''

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    encryption: ssl
    auth_mode: login
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: info@contentarena.com
        sender_name: Content Arena
    registration:
        confirmation:
            enabled: true # Must be true when SMTP server is ready.
            template:   Registration/email.txt.twig
        form:
            type: AppBundle\Form\RegistrationFormType
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template:   email/password_resetting.email.twig

fos_rest:
    routing_loader:
        default_format: json                            # All responses should be JSON formated
        include_format: false                           # We do not include format in request, so that all responses
                                                        # will eventually be JSON formated

knp_snappy:
    temporary_folder: "%kernel.cache_dir%/snappy"
    pdf:
        enabled:    true
        binary:     wkhtmltopdf
        options:    []


easy_admin:
    site_name: 'Content Arena'
    entities:
            User:
                class: AppBundle\Entity\User
                list:
                    fields: ['id', 'firstName', 'lastName', 'email', 'approved', 'profile', 'status']
                    actions:
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
                        - { name: 'createCompany' }

                form:
                    fields:
                        - 'email'
                        - 'firstName'
                        - 'lastName'
                        - 'profile'
                        - 'status'
                        - 'title'
                        - 'phone'
                        - 'country'
                        - 'company'

            Company:
                class: AppBundle\Entity\Company
                controller: AppBundle\Controller\Admin\CompanyController
                form:
                    fields:
                        - 'legalName'
                        - 'displayName'
                        - 'website'
                        - 'address'
                        - 'owner'
                        - 'zip'
                        - 'phone'
                        - 'description'
                        - 'year'
                        - 'size'
                        - 'country'
            Content:
                class: AppBundle\Entity\Content
                list:
                    fields:
                        - { property: 'customId' }
                        - { property: 'company' }
                        - { property: 'sport' }
                        - { property: 'createdAt' }
                        - { property: 'image', type: 'image', base_path: '%admin_uploads_uri%' }
                        - { property: 'ownLicense', template: ':easy_admin:license.list.html.twig', base_path: '%admin_uploads_uri%' }
                        - { property: 'brochure', template: ':easy_admin:brochure.list.html.twig', base_path: '%admin_uploads_uri%' }
                        - { property: 'approved' }
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
            Status:
                class: AppBundle\Entity\UserStatus
            RightsPackage:
                class: AppBundle\Entity\RightsPackage
                label: 'Rights Package'
                list:
                    fields:
                        - 'name'
                        - 'children'
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
                form:
                    fields:
                        - 'name'
                        - 'children'
            Rights:
                class: AppBundle\Entity\Rights
                label: 'Rights'
                list:
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
            RightsItemContent:
                class: AppBundle\Entity\RightsItemContent
                label: 'Rights Items'
                form:
                    label: 'Rights Items'
                    fields:
                        - 'name'
                        - 'form_content'
                        - 'contract_content'
                        - 'description'
                        - 'children'
                        - { property: 'not_optional', type: 'checkbox' }
                list:
                    label: 'Rights Items'
                    actions:
                        - { name: 'show', icon: 'eye', label: '' }
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
            EmailContent:
                class: AppBundle\Entity\EmailContent
                label: 'Email Content'
                list:
                    fields: ['slug', 'description', 'content']
                    actions:
                        - { name: 'edit', icon: 'pencil', label: '' }
                        - { name: 'delete', icon: 'times', label: '' }
                form:
                    fields: ['slug', 'description', 'content']
            Profile:
                class: AppBundle\Entity\Profile
knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
