imports:
    - { resource: config.yml }
    - { resource: services_test.yml}

parameters:
    app.email_alerts: 'alexander@contentarena.com'
    google_analytics_key: 'UA-136237491-2'

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_test.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped
        grouped:
            type:    group
            members: [nested, deduplicated]
        deduplicated:
            type:    deduplication
            handler: swift
        swift:
            type:         swift_mailer
            from_email:   'error-test-no-reply@contentarena.com'
            to_email:     ['juancruztalco@gmail.com']
            subject:      'An Error Occurred! %%message%%'
            level:        debug
            formatter:    monolog.formatter.html
            content_type: text/html
        nested:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 10
        console:
            type: console
            process_psr_3_messages: false
        app:
            # log all messages (since debug is the lowest level)
            level:    debug
            type:     stream
            path:     '%kernel.logs_dir%/app.log'
            channels: [app]
