api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

content_arena_layer:
    resource: "@ContentArenaLayerBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin


api_rest:
    type: rest
    resource: ApiBundle\Controller\LoginController
    prefix:   /v1/auth

api_rest_utils:
    type: rest
    resource: ApiBundle\Controller\UtilsController
    prefix:   /v1/utils