# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /
                use_referer : true
            entry_point: service.entry_point
            logout:
                path: /logout
                target: /
                invalidate_session: true
            anonymous:    true
            switch_user:  { role: ROLE_ADMIN, parameter: _ghost_mode }

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/landing$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/auth/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/pre/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/password/recover, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/password/update, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/code, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/activate, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/search/countries/all, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/search/sports/all, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/search/sports/groups, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/search/territories, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/search/regions, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/content/preview, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/generalterms, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public/listing, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/api, role: ROLE_USER }
        - { path: ^/api/notifications/all/visited, role: ROLE_USER }
        - { path: ^/api/notifications/, role: ROLE_USER }
        - { path: ^/api/notifications/visited, role: ROLE_USER }
        - { path: ^/api/notifications/seen, role: ROLE_USER }
        - { path: ^/api/notifications/remove, role: ROLE_USER }

        - { path: ^/contract, role: ROLE_USER }
        - { path: ^/listings, role: ROLE_USER }
        - { path: ^/listing, role: ROLE_USER }
        - { path: ^/terms, role: ROLE_USER }
        - { path: ^/license, role: ROLE_USER }
        - { path: ^/settings, role: ROLE_USER }
        - { path: ^/messages, role: ROLE_USER }
        - { path: ^/marketplace, role: ROLE_USER }
        - { path: ^/managelistings, role: ROLE_USER }
        - { path: ^/commercialoverview, role: ROLE_USER }
        - { path: ^/properties, role: ROLE_USER }
        - { path: ^/watchlist, role: ROLE_USER }
        - { path: ^/createproperty, role: ROLE_USER }
        - { path: ^/bids, role: ROLE_USER }
        - { path: ^/closeddeals, role: ROLE_USER }
        - { path: ^/content/draft, role: ROLE_USER }
        - { path: ^/contentlisting, role: ROLE_USER }

        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/test, role: ROLE_ADMIN }
