# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /

            logout:       true
            anonymous:    true
            switch_user:  { role: ROLE_ADMIN, parameter: _ghost_mode }

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/auth/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/code, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/activate, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/generalterms, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/contract, role: ROLE_USER }
        - { path: ^/listings, role: ROLE_USER }
        - { path: ^/listing, role: ROLE_USER }
        - { path: ^/license, role: ROLE_USER }
        - { path: ^/settings, role: ROLE_USER }
        - { path: ^/messages, role: ROLE_USER }
        - { path: ^/marketplace, role: ROLE_USER }
        - { path: ^/managelistings, role: ROLE_USER }
        - { path: ^/commercialoverview, role: ROLE_USER }
        - { path: ^/watchlist, role: ROLE_USER }
        - { path: ^/api, role: ROLE_USER }
        - { path: ^/bids, role: ROLE_USER }
        - { path: ^/closeddeals, role: ROLE_USER }
        - { path: ^/content/draft, role: ROLE_USER }
