# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_fe:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Lint FE code
      - run:
          name: Linting
          command: npm run lint

      # TODO Run Tests

      # Build project with different configuration based on
      # the current branch
      - run:
          name: Building
          command: |
            if [ "${CIRCLE_BRANCH}" == "development" ]; then
                npm run dev
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run prod
            else
                npm run dev
            fi
            
  - save_cache:
      key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      paths:
        - web/assets

  # TODO add BE build

  deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - run:
          name: Upload FE files
          command: echo ${CIRCLE_BRANCH}

workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
  jobs:
    - build
    # The deploy job will only run on the filtered branches and
    # require the build job to be successful before it starts
    - deploy:
        requires:
          - build_fe
        filters:
          branches:
            only:
              - development
