FOS\UserBundle\Model\User:
   properties:
      plainPassword:
        - NotBlank: { message: "Please enter a password", groups:[Registration, ResetPassword, ChangePassword] }
        - Length:
                        min: 8
                        max: 50
                        minMessage: "Your first name must be at least {{ limit }} characters length"
                        maxMessage: "Your first name cannot be longer than {{ limit }} characters length"
